# -*- coding: utf-8 -*-
"""MACHINE LEARNING ESSENTIALS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOCnCuASnnwSTNBZ_LX00JYZxewbDhDQ

**Practical:02 Create a scalar, a vector, and a matrix using NumPy. Display their dimensions and
data types.**
"""

import numpy as np
List1=np.array([1,2,3,4,5])
List2=np.array([10,20,30,40,50])
result=List1+List2
print(result)

print(result.shape)

print(result.dtype)

print(result.ndim)

"""**Practical 04 :Demonstrate NumPy broadcasting using a scalar and a vector with a suitable
example.**


"""

scalar=np.array(20)
print(scalar)
print(scalar.shape)
print(scalar.dtype)
print(scalar.ndim)
result2=List1*scalar
print(result2)

"""**Practical:05 Given two vectors, compute their dot product and explain its significance in
machine learning.**
"""

output=np.dot(List1,List2)
print(output)

"""**Practical: 06 Compute the projection of one vector onto another using NumPy.**

projection = (a.b/b.b)*b
"""

import numpy as np
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
projection=((np.dot(a,b)/np.dot(b,b))*b)
print(projection)

"""**Practical 07: Create two vectors and check whether they are orthogonal. Normalize one vector
and verify its magnitude.**
"""

vector1=np.array([1,-1,0])
vector2=np.array([1,-1,0])
dot_product=np.dot(vector1,vector2)
print("Dot product:",dot_product)

if dot_product==0:
    print("The vectors are orthogonal")
else:
    print("The vectors are not orthogonal")

magnitude=np.linalg.norm(vector1)
vector1_normalized=vector1/magnitude

print("Magnitude of vector1:",magnitude)
print("Normalized vector1:",vector1_normalized)
print("Magnitude after normalization:",np.linalg.norm(vector1_normalized))

print("Magnitude of vector1:",round(magnitude,3)) #that's why here the 'round' command are important
print("Normalized vector1:",np.round(vector1_normalized,3))
print("Magnitude after normalization:",round(np.linalg.norm(vector1_normalized),3))

"""Practical 08: For a any given vector, compute mean, variance, and standard deviation using
NumPy (Verify the mean, variance and Std manually-hand written).

"""

data=np.array([10,20,30,40,50])

print("Mean",np.mean(data))
print("variance",np.var(data))
print("standard deviation",round(np.std(data)))

"""**Practical 09: Create a multivariate data matrix and compute its covariance matrix and
correlation matrix (Then, manually verify the covariance and correlation
calculations using mathematical formulas-hand written)**
"""

data=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
cov_matrix=np.cov(data.T)
corr_matrix=np.corrcoef(data.T)

print("covariance Matrix:\n",np.round(cov_matrix,3))
print(    )
print("correlation Matrix:\n",np.round(corr_matrix,3))

"""**Practical 10: Create a square matrix and compute its rank, determinant, and inverse (if it
exists).**
"""

import numpy as np
A = np.array([[1,2,3],
              [0,1,4],
              [5,6,0]])
print(A)
rank=np.linalg.matrix_rank(A)
print("rank:",rank)

determinant = np.linalg.det(A)
print("determinant:",int(round(determinant,3)))

A

rank

A_inv= np.linalg.inv(A)
print("Inverse of A:\n",A_inv)

"""**Practical 11.Compute the eigenvalues and eigenvectors of a given matrix and verify the
eigenvalue equation.**
"""

A=np.array([[2,0],
            [0,3]])
values,vectors=np.linalg.eig(A)
print("Eigenvalues:\n", values)
print("Eigenvectors:\n",vectors)

"""**Practical 12 : Apply a linear transformation to a vector using a matrix and explain its effect.**"""

#verification
#Av-yv=0
#Av=yv
print("left side:\n",A@vectors)
print("right side:",values[0]*vectors[:,0])

"""# Pandas

**Lab Expt: Experiencing Pandas Library & Data Handling**

**Dataset: students.csv**

**1. Dataset Loading and Exploration:  
Load the dataset using Pandas and display the first five records. Identify the number of
rows and columns, data types, and missing values.**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile students.csv
# 
# student_id,age,gender,marks,attendance,city,parent_income,study_hours,remarks
# 101,20,Male,78,85, Delhi ,45000,3,Good
# 102,21,Female,65,90,Mumbai,52000,2,average
# 103,19,Male,88,92,Chennai,48000,4,Excellent
# 104,22,Female,45,70,Bangalore,39000,1, poor
# 105,20,Male,,80,Hyderabad,41000,2,Good
# 106,21,Female,92,95,delhi,60000,5,EXCELLENT
# 107,23,Male,34,60,Mumbai,35000,1,poor
# 108,20,Female,76,,Chennai,47000,3,Average
# 109,22,Male,110,88,Bangalore,58000,4,Excellent
# 110,21,Female,58,75,Hyderabad,,2,good
# 111,20,Male,78,85,Delhi,45000,3,Good
# 112,19,Female,-5,82, Chennai,42000,2,poor
# 113,24,Male,67,91,MUMBAI,51000,3,Average
# 114,,Female,81,89,Bangalore,54000,4,Excellent
# 115,21,Male,NaN,65,Hyderabad,38000,1,poor
# 116,20,Female,73,87,Delhi,46000,3,Good
# 117,19,,55,78,Delhi,43000,2,Average
# 118,twenty,Male,60,80,Mumbai,48000,3,Good
# 119,22,FEMALE,85,95, Bangalore ,70000,5,EXCELLENT
# 120,21,Male,40,100,Chennai,39000,0, poor
# 121,20,Female,39,55,,42000,1,average
# 122,23,Male,72,85,Delhi,N/A,3,Good
# 123,21,Female,68,92,Hyderabad,50000,,Average
# 124,22,Male,90,110,Mumbai,65000,6,Excellent
# 125,19,Female,abc,70,Chennai,41000,2,poor
# 126,20,Male,75,88,del hi,45000,3,Good
# 127,21,Female,82,89,DELHI,52000,4,Excellent
# 128,20,Male,78,85,Delhi,45000,3,Good
# 128,20,Male,78,85,Delhi,45000,3,Good
#

import pandas as pd
df = pd.read_csv("students.csv")
print(df)

df.head()

df.shape

df.tail()

df.info()

df.describe()

df.sample()

df.isnull()

df.isnull().sum()

"""**2. Data Selection and Filtering:
Select only age, marks, and attendance columns. Filter students with marks greater than
70 and display the first five records.**
"""

df[df['age'].isnull()]

df[df[['marks','attendance','age']].isnull().any(axis=1)]

import pandas as pd
df['marks'] = pd.to_numeric(df['marks'], errors='coerce')

mean_marks = df['marks'].mean()
df['marks'] = df['marks'].fillna(mean_marks)
print(df['marks'])

df.drop_duplicates()

df = df.dropna(subset=['attendance'])

df['age'] = pd.to_numeric(df['age'], errors='coerce')
median_age = df['age'].median()
df['age'] = df['age'].fillna(median_age)

df['gender'] = df['gender'].str.lower().str.strip()
mode_gender = df['gender'].mode()[0]
df['gender'] = df['gender'].fillna(mode_gender)
print(f"Most common gender used for fill: {mode_gender}")

median_hours = df['study_hours'].median()
df['study_hours'] = df['study_hours'].fillna(median_hours)

df['city']= df['city'].str.lower().str.strip()
df['city'] = df['city'].fillna('Rajkot')

df.isnull().sum()

#create a normalization Marks column

min_marks = df['marks'].min()
max_marks = df['marks'].max()

df['normalized_marks'] = (df['marks'] - min_marks) / (max_marks - min_marks)

#create a pass status column
import numpy as np

df['pass_status'] = np.where(df['marks'] >= 50, 'Pass', 'Fail')

df['city'].unique()

df['city']= df['city'].str.replace(" "," ")

avg_attendance_per_city = df.groupby('city')['attendance'].mean()
print(avg_attendance_per_city)

avg_marks_by_gender = df.groupby('gender')['marks'].mean()
print(avg_marks_by_gender)

#count students per city

student_count_per_city = df['city'].value_counts()
print(student_count_per_city)

df['marks'] = df['marks'].clip(lower=0,upper=100)

df['attendance'] = df['attendance'].clip(lower=0,upper=100)

df

"""# Matplotlib

"""

#a) Plot a histogram of the marks varibale to examine the
#distribution of the student performance

import matplotlib.pyplot as plt

plt.figure()
plt.hist(df['marks'],bins=8)
plt.xlabel('marks')
plt.ylabel('Number of students')
plt.title('Distribution of students Marks')
plt.show()

plt.figure()
plt.scatter(df['study_hours'],df['marks'])
plt.xlabel('study_hours')
plt.ylabel('marks')
plt.title('study hours and marks')
plt.show()

""". Build a Simple Linear Regression model to determine the relationship between
student attendance and marks using the provided dataset. After splitting the data
and training your model, visualize the results with a scatter plot and the
regression line, and evaluate the model's performance using R-squared (R2) and
Mean Squared Error (MSE).
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
#select features and target
X=df[['attendance']]
y=df['marks']
# split data
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2,random_state=42)

#cretae model
model=LinearRegression()
#train model
model.fit(xtrain,ytrain)
#predict on the data
ypred=model.predict(xtest)
# evaluate model
print("R2 score:",round(r2_score(ytest,ypred),4))
print("MSE:",round(mean_squared_error(ytest,ypred),4))

"""3. Implement a Logistic Regression model to predict student pass_status based on
attendance, study_hours, age, and parent_income. Apply feature scaling and
provide a detailed classification report that evaluates the model's performance for
both 'Pass' and 'Fail' categories.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report
x=df[['attendance','study_hours','age','parent_income']].copy()

# Impute missing values in 'parent_income' column with its median
median_parent_income = x['parent_income'].median()
x['parent_income'] = x['parent_income'].fillna(median_parent_income)

le = LabelEncoder()
y = le.fit_transform(df['pass_status'])
#split data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42,stratify=y)
scaler = StandardScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
# model
model = LogisticRegression(class_weight = 'balanced',max_iter=2000)
model.fit(xtrain_scaled,ytrain)
ypred = model.predict(xtest_scaled)
print("classification report")
print(classification_report(ytest,ypred,target_names=le.classes_, zero_division=0))

df.isnull().sum()

